/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kz.pashim

import kz.pashim.patterns.structural.factory.AppleGadgetFactory
import kz.pashim.patterns.structural.factory.MiGadgetFactory
import kz.pashim.patterns.structural.factory.PhoneVersion
import java.lang.IllegalArgumentException

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val factory = when (args.first()) {
        "apple" -> AppleGadgetFactory()
        "mi" -> MiGadgetFactory()
        else -> throw IllegalArgumentException()
    }

    print(factory.createSmartPhone(PhoneVersion.V2).getInfo())
}
