/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kz.pashim

import kz.pashim.patterns.structural.singleton.GadgetShop

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val shop = GadgetShop.instance
    shop.buySmartPhone(args)
}
